FROM node:18-alpine AS builder
WORKDIR /app
COPY . .
RUN yarn install --production

# Stage 2: Runtime Stage
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app .
CMD ["node", "app.js"]
EXPOSE 4000
